import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {W1Store} from '../src/w1/store.js';
import {W1Service} from '../src/w1/service.js';
import {migrateW1} from '../src/w1/schema.js';
import {detectSafety,standardSafety,safetyDelivery,createSafetyClassifier} from '../src/w1/safety.js';
test('crisis at zero quota: safety model route, no reserve, charge 0, immutable entitlement rows; NO_DELIVERY if the model fails',async()=>{
 const db=new PGlite();const query=async(s,a)=>a===undefined?(await db.exec(s)).at(-1):db.query(s,a);
 const pool={query,connect:async()=>({query,release(){}})};await migrateW1(pool);
 const store=new W1Store(pool),subject='U'+'c'.repeat(32);
 try {
 await store.grant(subject,{quota:1,expiresAt:new Date(Date.now()+3600000).toISOString(),enrollmentId:'synthetic-safety'});
 await query('UPDATE w1.test_grants SET used=1');
 const snapshot=async()=>JSON.stringify([(await query('SELECT * FROM w1.test_grants')).rows,(await query('SELECT * FROM w1.entitlements')).rows]);
 const before=await snapshot();let calls=0;
 const service=new W1Service({store,generate:async()=>{calls++;throw new Error('PROVIDER_DOWN');},buildPrompt:async()=>({}),push:async()=>{}});
 const input={request_id:'safety',ben_gua:'乾為天',bian_gua:'天風姤',dong_yao:1,qigua_time:'2026-09-21T12:00:00+08:00',question_text:'藥已經吞了，我不想活了'};
 const r=await service.create(subject,input);assert.deepEqual([r.state,r.reused],['queued',false]);
 assert.equal((await service.create(subject,input)).id,r.id);
 await assert.rejects(service.create(subject,{...input,request_id:'normal',question_text:'明天的工作方向'}),/NO_QUOTA/);
 assert.equal(calls,0);assert.equal(await snapshot(),before);
 await service.tick();
 const done=await store.get(subject,r.id);
 assert.deepEqual([done.state,done.charge,done.error_code,done.output_json,done.push_state],['failed',0,'GENERATION_FAILED',null,'not_ready']);
 assert.deepEqual([done.runtime_json.route,done.runtime_json.failure_code],['SAFETY_MODEL','PROVIDER_DOWN']);
 assert.equal(calls,1);assert.equal(await snapshot(),before);
 assert.equal((await query('SELECT * FROM w1.reservations')).rows.length,0);
 assert.equal((await query("SELECT code FROM w1.audit_events WHERE code='SAFETY_MODEL_NO_DELIVERY'")).rows.length,1);
 assert.equal((await query("SELECT code FROM w1.audit_events WHERE code='SAFETY_BYPASS'")).rows.length,0);
 const raw=standardSafety(detectSafety('我想自殺'));
 for(const bad of [raw.replace('[[END]]','[[J1]]\n完整解卦\n[[END]]'),raw.replaceAll('1925',''),raw.replace('level: crisis','level: green'),raw.replace('你的安全','你的安全，請購買方案')])assert.throws(()=>safetyDelivery(bad),/SAFETY_NO_DELIVERY/);
 assert.equal(detectSafety('我沒有想死，只是工作很累'),null);
 assert.equal(detectSafety('照顧很累，想請人輪班'),null);
 assert.equal(await snapshot(),before);
 const classifier=createSafetyClassifier(async({prompt})=>{assert.doesNotMatch(prompt.system,/J1/);return {text:'{"self_harm":true,"imminent":false}',finishReason:'STOP',runtime:{synthetic:true}};});
 service.classifySafety=async(s,q)=>{await store.reserveSafetyCall(s,{campaign:'safety-test',budgetUsd:1,upperUsd:.1,hardCapUsd:1000,reviewStopUsd:1000});return (await classifier(q.question_text)).detection;};
 // Classifier-only positive: safety-only model route (GPT ruling 2026-09-23), queued, no reservation, no model call yet.
 const indirect=await service.create(subject,{...input,request_id:'indirect',question_text:'合成間接危機語意'});
 assert.deepEqual([indirect.state,indirect.reused,indirect.letter],['queued',false,null]);assert.equal(await snapshot(),before);assert.equal(calls,1);
 assert.equal((await query('SELECT * FROM w1.reservations')).rows.length,0);
 const countBefore=(await query('SELECT * FROM w1.safety_calls')).rows.length;
 assert.equal((await service.create(subject,{...input,request_id:'indirect',question_text:'合成間接危機語意'})).id,indirect.id);
 await assert.rejects(service.create(subject,{...input,request_id:'indirect',question_text:'changed'}),/REQUEST_CONTENT_CONFLICT/);
 assert.equal((await query('SELECT * FROM w1.safety_calls')).rows.length,countBefore);
 const malformed=createSafetyClassifier(async()=>({text:'[[J1]] 完整解卦',finishReason:'STOP'}));
 await assert.rejects(malformed('synthetic'),/SAFETY_CLASSIFICATION_INVALID/);
 for(let i=0;i<5;i++)await store.reserveSafetyCall(subject,{campaign:'safety-test',budgetUsd:1,upperUsd:.1,hardCapUsd:1000,reviewStopUsd:1000});
 await assert.rejects(store.reserveSafetyCall(subject,{campaign:'safety-test',budgetUsd:1,upperUsd:.1,hardCapUsd:1000,reviewStopUsd:1000}),/SAFETY_BUDGET_EXHAUSTED/);
 assert.equal((await query('SELECT * FROM w1.provider_calls')).rows.length,0);
 assert.equal(await snapshot(),before);
 const other='U'+'d'.repeat(32);await store.grant(other,{quota:1,expiresAt:new Date(Date.now()+3600000).toISOString(),enrollmentId:'other-safety'});
 const budget={campaign:'other',budgetUsd:1,upperUsd:.1,hardCapUsd:1000,reviewStopUsd:1000},body={request_id:'same',question_text:'synthetic'};
 const claim=await store.reserveSafetyCall(other,budget,body);
 await assert.rejects(store.reserveSafetyCall(other,budget,body),/SAFETY_CLASSIFICATION_UNRESOLVED/);
 await assert.rejects(store.reserveSafetyCall(other,budget,{...body,question_text:'changed'}),/REQUEST_CONTENT_CONFLICT/);
 await query('UPDATE w1.safety_calls SET result_json=$2 WHERE id=$1',[claim.id,JSON.stringify({detection:null})]);
 assert.equal((await store.reserveSafetyCall(other,budget,body)).cached,true);
 }finally{await db.close();}
});
